#!/bin/sh
### BEGIN INIT INFO
# Provides:             automountservice
# Should-Start:         console-screen kbd acpid dbus hal consolekit
# Required-Start:       $local_fs $remote_fs x11-common
# Required-Stop:        $local_fs $remote_fs
# Default-Start:        S 2 3 4 5
# Default-Stop:         0 1 6
# Short-Description: 	Automount storage service
# Description:       	Automount storage service
### END INIT INFO

export PATH=/system/urus/bin:/bin:/sbin:/usr/bin:/usr/sbin:$PATH

PLATOS=`cat /etc/os-release | grep -rwi - -e "ID" | cut -f2 -d=`

case $1 in
	start)
	printf "Starting automount disks...\n"
		automountdisks 2>/dev/null &
		;;
	stop)
		killall -s KILL automountdisks
		;;
	restart)
		stop
		start
		;;
	status)
		;;
	*)
		echo "Usage: $0 {start|stop|status|restart}"
esac

